[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none'"
Referrer-Policy = "no-referrer"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
